#!/bin/sh
# ── Hermes-WRT First Boot Settings ──

# Set Hostname
uci set system.@system[0].hostname='HermesWrt'

# Set Timezone to Asia/Jakarta (WIB)
uci set system.@system[0].timezone='WIB-7'
uci set system.@system[0].zonename='Asia/Jakarta'
uci commit system

# Set Google DNS as default DNS Forwarding for dnsmasq
uci add_list dhcp.@dnsmasq[0].server='8.8.8.8'
uci add_list dhcp.@dnsmasq[0].server='8.8.4.4'
uci commit dhcp

# Set default theme to luxe if available, fallback to bootstrap
if [ -d /www/luci-static/luxe ]; then
    uci set luci.main.mediaurlbase='/luci-static/luxe'
    uci commit luci
fi

exit 0
